<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-F6NS1F9" name="com.training.sanity.tests.RTTC_022" tests="6" failures="0" timestamp="11 Mar 2019 08:56:32 GMT" time="12.887" errors="1">
  <testcase name="setUp" time="10.305" classname="com.training.sanity.tests.RTTC_022"/>
  <testcase name="displayReportsOptions" time="0.544" classname="com.training.sanity.tests.RTTC_022"/>
  <testcase name="displaySalesOptions" time="0.510" classname="com.training.sanity.tests.RTTC_022"/>
  <testcase name="navigateToOrdersPage" time="0.733" classname="com.training.sanity.tests.RTTC_022"/>
  <testcase name="displayGroupByListBox" time="0.001" classname="com.training.sanity.tests.RTTC_022">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.training.pom.RTTC_022POM.displayGroupByListboxOptions(RTTC_022POM.java:131)
at com.training.sanity.tests.RTTC_022.displayGroupByListBox(RTTC_022.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- displayGroupByListBox -->
  <testcase name="filterOrderDetails" time="0.794" classname="com.training.sanity.tests.RTTC_022"/>
</testsuite> <!-- com.training.sanity.tests.RTTC_022 -->
